### ISSUE TITLE
Proper macOS support for API identities

### ISSUE THREAD

**Issue by megastep** [qonversion/qonversion-ios-sdk#542]
I have several universal iOS / macOS apps (not Catalyst - separate apps with a common code base). When running the macOS version, I get a bunch of these errors in the console:

```
❌ Request failed: https://api.qonversion.io/v2/identities, error: Error Domain=com.qonversion.io.api Code=3 "wrong platform" UserInfo={NSLocalizedDescription=wrong platform}
```

I believe the SDK sends the "macOS" platform to the API, which in turn returns this failure. This creates downstream issues as I think it prevents my users from being identified properly and re-associated with their other accounts.

It sounds like an easy fix would be to simply allow the backend to recognize macOS platform values, as otherwise all of the SDK compiles and is functional, and can process purchases, etc.

**Comment by suriksarkisyan** [comment]
Hi, @megastep 
I will discuss with the team and get back to you as soon as there are any updates!

**Comment by megastep** [comment]
was there any resolution on this?

**Comment by suriksarkisyan** [comment]
Hello, @megastep . The solution you provided above will work for now, even though it’s not ideal. The issue is that you need to ensure this change isn’t lost after the pod install. As for a proper solution, I’ve passed the task to the team to fix the problem. I can’t say exactly when it will be ready, but I will definitely get back to you with an update as soon as we release the fix.

**Comment by megastep** [comment]
I am using my patched fork with the Swift Package Manager so no worries for now. I'd love to know when I can safely switch back to the mainstream package though...

**Comment by smejl** [comment]
Hi Stephane,

We've fixed that on our end, so you can freely switch back to SPM.
